module.exports = {
  apps: [
    {
      name: 'nest-gateway',
      script: 'dist/apps/gateway/main.js',
      instances: 'max', // 使用集群模式，根据CPU核心数自动调整
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        GATEWAY_PORT: 3000,
        MAIN_SERVICE_HOST: 'localhost',
        MAIN_SERVICE_PORT: 3001,
        CONTENT_SERVICE_HOST: 'localhost',
        CONTENT_SERVICE_PORT: 3004,
        MAIN_HTTP_PORT: 3011,
        CONTENT_HTTP_PORT: 3014,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/gateway-error.log',
      out_file: 'logs/gateway-out.log',
    },
    // 微服务组 - 用于微服务通信
    {
      name: 'nest-main',
      script: 'dist/apps/main/main.js',
      instances: 1,
      // exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        MAIN_SERVICE_PORT: 3001,
        CONTENT_SERVICE_HOST: 'localhost',
        CONTENT_SERVICE_PORT: 3004,
        MAIN_HTTP_PORT: 3011,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3001,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/main-error.log',
      out_file: 'logs/main-out.log',
    },
    {
      name: 'nest-content',
      script: 'dist/apps/content/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
        CONTENT_SERVICE_PORT: 3004,
        CONTENT_HTTP_PORT: 3014,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/content-error.log',
      out_file: 'logs/content-out.log',
    },
    // 单体服务 - 独立运行
    {
      name: 'nest-admin',
      script: 'dist/apps/admin/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: 'logs/admin-error.log',
      out_file: 'logs/admin-out.log',
    },
  ],
};
